language: node_js
node_js:
  - "10"

before_install:
  - npm install -g @angular/cli


install: npm install

branches:
  only:
    - master


deploy:
  provider: heroku
  app: alla-clicker
  api_key:
    secure: "e16329af-9f34-443a-9957-e3f6158dc5e2"

